package ch.vorburger.blueprints.ui.html.i18n.tests;

import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Learning ResourceBundle.
 * 
 * This class was generated by Eclipse Source > Externalize Strings - but badly?
 *
 * @author Michael Vorburger
 */
public class Messages {
	private static final String BUNDLE_NAME = "ch.vorburger.blueprints.ui.html.i18n.tests.messages"; //$NON-NLS-1$

	// NO, never! private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

	private Messages() {
	}

	public static String getString(String key, Locale locale) throws MissingResourceException {
		return ResourceBundle.getBundle(BUNDLE_NAME, locale).getString(key);
	}
}
