package ch.vorburger.uftam.sample.vaadin.smartform;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;

public class SampleFormView extends CustomComponent {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private CheckBox checkBox_1;
	@AutoGenerated
	private OptionGroup optionGroup_1;
	@AutoGenerated
	private ComboBox comboBox_3;
	@AutoGenerated
	private PopupDateField popupDateField_1;
	@AutoGenerated
	private ComboBox comboBox_2;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private TextField textField_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SampleFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public TextField getTextField_1() {
		return textField_1;
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setColumns(2);
		mainLayout.setRows(5);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setCaption("Name:");
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		textField_1.setSecret(false);
		mainLayout.addComponent(textField_1, 0, 0);
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setCaption("Colour:");
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("-1px");
		comboBox_1.setHeight("-1px");
		mainLayout.addComponent(comboBox_1, 1, 0);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setCaption("Colour:");
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		textField_2.setSecret(false);
		mainLayout.addComponent(textField_2, 0, 1);
		
		// comboBox_2
		comboBox_2 = new ComboBox();
		comboBox_2.setCaption("Country:");
		comboBox_2.setImmediate(false);
		comboBox_2.setWidth("-1px");
		comboBox_2.setHeight("-1px");
		mainLayout.addComponent(comboBox_2, 1, 1);
		
		// popupDateField_1
		popupDateField_1 = new PopupDateField();
		popupDateField_1.setCaption("Date:");
		popupDateField_1.setImmediate(false);
		popupDateField_1.setWidth("-1px");
		popupDateField_1.setHeight("-1px");
		popupDateField_1.setInvalidAllowed(false);
		popupDateField_1.setResolution(4);
		mainLayout.addComponent(popupDateField_1, 0, 2);
		
		// comboBox_3
		comboBox_3 = new ComboBox();
		comboBox_3.setCaption("State:");
		comboBox_3.setImmediate(false);
		comboBox_3.setWidth("-1px");
		comboBox_3.setHeight("-1px");
		mainLayout.addComponent(comboBox_3, 1, 2);
		
		// optionGroup_1
		optionGroup_1 = new OptionGroup();
		optionGroup_1.setImmediate(false);
		optionGroup_1.setWidth("-1px");
		optionGroup_1.setHeight("-1px");
		mainLayout.addComponent(optionGroup_1, 0, 3);
		
		// checkBox_1
		checkBox_1 = new CheckBox();
		checkBox_1.setCaption("Check something:");
		checkBox_1.setImmediate(false);
		checkBox_1.setWidth("-1px");
		checkBox_1.setHeight("-1px");
		mainLayout.addComponent(checkBox_1, 1, 3);
		
		// label_1
		label_1 = new Label();
		label_1.setCaption("Try: Amount > 100 enables Date, ... ");
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Label");
		mainLayout.addComponent(label_1, 0, 4);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Save");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, 1, 4);
		mainLayout.setComponentAlignment(button_1, new Alignment(48));
		
		return mainLayout;
	}
	
}
