package ch.vorburger.blueprint.interactionframework.odata4j.example;
import ch.vorburger.blueprint.interactionframework.odata4j.AbstractInteractionFrameworkODataProducerImpl;


public class ExampleInteractionFrameworkODataProducerImpl extends AbstractInteractionFrameworkODataProducerImpl {

}
